#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
#Unofficial Bash Strict Mode http://redsymbol.net/articles/unofficial-bash-strict-mode/

exec >>/var/log/openvpn-daemon.log
exec 2>&1

[[ -e /var/run/openvpn-daemon/pid ]] && rm -f /var/run/openvpn-daemon/pid
mkdir -p /var/run/openvpn-daemon

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

mkdir -p /dev/net
[[ ! -c /dev/net/tun ]] && mknod /dev/net/tun c 10 200

CONFIG_DIR="${CONFIG_DIR:-/vpn}"

# support for OpenVPN locate command
# use case: 
#    select random config from the pool and 
#    do a basic healthcheck
if [ ! -z "$OVPN_CONFIG_LOCATE_CMD" ]; then
    cfg_path="$($OVPN_CONFIG_LOCATE_CMD)"
    if [ $? -eq 0 ]; then
        OVPN_CONFIG="$cfg_path"
    fi
fi
OVPN_CONFIG="${OVPN_CONFIG:-$CONFIG_DIR/config.ovpn}"

chmod 400 "$CONFIG_DIR/auth.txt"

echo "Starting OpenVPN daemon"
exec /usr/sbin/openvpn --config "$OVPN_CONFIG" --redirect-gateway --auth-user-pass "$CONFIG_DIR/auth.txt" --auth-nocache
