version: '3'

services:
  ovpn:
    container_name: ovpn
    image: mkorenkov/ovpn:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    volumes:
      - ./configs/us2194.nordvpn.com.tcp.ovpn:/vpn/config.ovpn
      - ./configs/auth.txt:/vpn/auth.txt
    ports:
      - 8118:8118
    cap_add:
      - NET_ADMIN
    network_mode: bridge

  # auto update containers
  watchtower:
    container_name: watchtower
    hostname: watchtower
    image: v2tec/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30
    network_mode: bridge
  
  # restart containers failing healthchecks
  autoheal:
    container_name: autoheal
    hostname: autoheal
    image: willfarrell/autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: none

  # cleanup leftovers
  dockergc:
    container_name: dockergc
    hostname: dockergc
    image: clockworksoul/docker-gc-cron:latest
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    environment:
        # By default, docker-gc is run every night at midnight. Change this variable to override.
        - CRON=0 9,21 * * *
        # By default, docker will not remove an image if it is tagged in multiple repositories. If
        # you have a server running docker where this is the case, for example in CI environments
        # where dockers are being built, re-tagged, and pushed, you can set this flag to 1 to override.
        - FORCE_IMAGE_REMOVAL=1
        # By default, if an error is encountered when cleaning up a container, Docker will report the
        # error back and leave it on disk. This can sometimes lead to containers accumulating. If
        # you run into this issue, you can force the removal of the container by setting this flag.
        - FORCE_CONTAINER_REMOVAL=1
        # By default, docker-gc will not remove a container if it exited less than 1 hour ago.
        # Set the GRACE_PERIOD_SECONDS variable to override this default.
        - GRACE_PERIOD_SECONDS=86400
        # By default, docker-gc will proceed with deletion of containers and images. To test your
        # settings set the DRY_RUN variable to override this default
        - DRY_RUN=0
        # By default, this process will leave any dangling volumes untouched. To instruct the
        # process to automatically clean up any dangling volumes, simply set this value to 1.
        - CLEAN_UP_VOLUMES=1
        # If you don't like all your log output and cron times being in UTC, you can set the
        # TZ variable to override the default.
        - TZ=America/Los_Angeles
    network_mode: none
