version: '3'

services:
  ovpn:
    container_name: ovpn
    image: mkorenkov/ovpn:latest
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    volumes:
      - ./configs/us2194.nordvpn.com.tcp.ovpn:/vpn/config.ovpn
      - ./configs/auth.txt:/vpn/auth.txt
    ports:
      - 8118:8118
    cap_add:
      - NET_ADMIN
    network_mode: host