#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
#Unofficial Bash Strict Mode http://redsymbol.net/articles/unofficial-bash-strict-mode/

exec >>/var/log/privoxy-daemon.log
exec 2>&1

[[ -e /var/run/privoxy-daemon/pid ]] && rm -f /var/run/privoxy-daemon/pid
mkdir -p /var/run/privoxy-daemon

[[ ! -f /etc/privoxy/privoxy.config ]] && cp /opt/privoxy.conf /etc/privoxy/privoxy.conf

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

exec privoxy --no-daemon /etc/privoxy/privoxy.conf